package com.transportportal.ui;

import com.transportportal.service.TransportService;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportsAuditPanel extends JPanel {
    private TransportService service;
    private DefaultTableModel reportsModel;
    private DefaultTableModel auditModel;
    private JTable reportsTable;
    private JTable auditTable;

    public ReportsAuditPanel(TransportService service) {
        this.service = service;
        initialize();
        loadSampleData();
    }

    private void initialize() {
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(10, 10, 10, 10));
        setBackground(new Color(245, 245, 245));

        // Title
        JLabel title = new JLabel("Reports & Audit Trail", SwingConstants.CENTER);
        title.setFont(new Font("Segoe UI", Font.BOLD, 18));
        title.setForeground(new Color(33, 150, 243));
        add(title, BorderLayout.NORTH);

        // Main content panel with tabs
        JTabbedPane contentTabs = new JTabbedPane();
        contentTabs.setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Reports Tab
        JPanel reportsPanel = createReportsPanel();
        contentTabs.addTab("📊 Reports", reportsPanel);

        // Audit Trail Tab
        JPanel auditPanel = createAuditPanel();
        contentTabs.addTab("🔍 Audit Trail", auditPanel);

        add(contentTabs, BorderLayout.CENTER);
    }

    private JPanel createReportsPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBackground(new Color(245, 245, 245));

        // Report type selection
        JPanel reportTypePanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10));
        reportTypePanel.setBackground(Color.WHITE);
        reportTypePanel.setBorder(BorderFactory.createTitledBorder("Report Type"));

        final JComboBox<String> reportTypeCombo = new JComboBox<String>(new String[]{
            "Booking Summary", "Revenue Report", "Trip Performance", "User Activity", "Vehicle Utilization"
        });

        final JTextField txtStartDate = new JTextField(10);
        txtStartDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        
        final JTextField txtEndDate = new JTextField(10);
        txtEndDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));

        JButton btnGenerate = new JButton("Generate Report");
        styleAddButton(btnGenerate);

        reportTypePanel.add(new JLabel("Report Type:"));
        reportTypePanel.add(reportTypeCombo);
        reportTypePanel.add(new JLabel("Start Date:"));
        reportTypePanel.add(txtStartDate);
        reportTypePanel.add(new JLabel("End Date:"));
        reportTypePanel.add(txtEndDate);
        reportTypePanel.add(btnGenerate);

        // Reports table
        reportsModel = new DefaultTableModel(new String[]{
            "Report ID", "Type", "Period", "Generated By", "Date", "Status"
        }, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        reportsTable = new JTable(reportsModel);
        reportsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        reportsTable.setRowHeight(30);
        JScrollPane reportsScroll = new JScrollPane(reportsTable);
        reportsScroll.setBorder(BorderFactory.createTitledBorder("Generated Reports"));
        
        // Report details panel
        final JTextArea reportDetails = new JTextArea();
        reportDetails.setEditable(false);
        reportDetails.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane detailsScroll = new JScrollPane(reportDetails);
        detailsScroll.setBorder(BorderFactory.createTitledBorder("Report Details"));
        detailsScroll.setPreferredSize(new Dimension(600, 300));

        // Split pane for table and details
        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, reportsScroll, detailsScroll);
        splitPane.setResizeWeight(0.6);

        // Reports buttons
        JPanel reportsButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        reportsButtonPanel.setBackground(new Color(245, 245, 245));
        
        JButton btnViewReport = new JButton("👁️ View Report");
        JButton btnExportPDF = new JButton("📄 Export PDF");
        JButton btnExportExcel = new JButton("📊 Export Excel");
        JButton btnRefreshReports = new JButton("🔄 Refresh");
        
        styleEditButton(btnViewReport);
        styleEditButton(btnExportPDF);
        styleEditButton(btnExportExcel);
        styleRefreshButton(btnRefreshReports);

        reportsButtonPanel.add(btnViewReport);
        reportsButtonPanel.add(btnExportPDF);
        reportsButtonPanel.add(btnExportExcel);
        reportsButtonPanel.add(btnRefreshReports);

        // Layout
        panel.add(reportTypePanel, BorderLayout.NORTH);
        panel.add(splitPane, BorderLayout.CENTER);
        panel.add(reportsButtonPanel, BorderLayout.SOUTH);

        // Add action listeners for reports
        btnGenerate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                generateReport((String) reportTypeCombo.getSelectedItem(), 
                             txtStartDate.getText(), txtEndDate.getText());
            }
        });

        btnViewReport.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                viewSelectedReport(reportDetails);
            }
        });

        btnExportPDF.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                exportReportToPDF();
            }
        });

        btnExportExcel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                exportReportToExcel();
            }
        });

        btnRefreshReports.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                refreshReportsData();
            }
        });

        return panel;
    }

    private JPanel createAuditPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBackground(new Color(245, 245, 245));

        // Audit filter panel
        JPanel filterPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10));
        filterPanel.setBackground(Color.WHITE);
        filterPanel.setBorder(BorderFactory.createTitledBorder("Filter Options"));

        final JComboBox<String> actionTypeCombo = new JComboBox<String>(new String[]{
            "All Actions", "User Login", "Booking Created", "Booking Modified", 
            "Payment Processed", "System Configuration", "Data Export"
        });

        final JTextField txtAuditStartDate = new JTextField(10);
        txtAuditStartDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        
        final JTextField txtAuditEndDate = new JTextField(10);
        txtAuditEndDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));

        final JTextField txtUserFilter = new JTextField(10);
        txtUserFilter.setText("");

        JButton btnFilter = new JButton("Apply Filter");
        styleEditButton(btnFilter);

        filterPanel.add(new JLabel("Action Type:"));
        filterPanel.add(actionTypeCombo);
        filterPanel.add(new JLabel("Start Date:"));
        filterPanel.add(txtAuditStartDate);
        filterPanel.add(new JLabel("End Date:"));
        filterPanel.add(txtAuditEndDate);
        filterPanel.add(new JLabel("User:"));
        filterPanel.add(txtUserFilter);
        filterPanel.add(btnFilter);

        // Audit table
        auditModel = new DefaultTableModel(new String[]{
            "ID", "Timestamp", "User", "Action", "Description", "IP Address", "Status"
        }, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        auditTable = new JTable(auditModel);
        auditTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        auditTable.setRowHeight(30);
        JScrollPane auditScroll = new JScrollPane(auditTable);
        auditScroll.setBorder(BorderFactory.createTitledBorder("Audit Trail Logs"));

        // Audit buttons
        JPanel auditButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        auditButtonPanel.setBackground(new Color(245, 245, 245));
        
        JButton btnViewDetails = new JButton("👁️ View Details");
        JButton btnExportAudit = new JButton("📄 Export Log");
        JButton btnClearFilter = new JButton("🗑️ Clear Filter");
        JButton btnRefreshAudit = new JButton("🔄 Refresh");
        
        styleEditButton(btnViewDetails);
        styleEditButton(btnExportAudit);
        styleDeleteButton(btnClearFilter);
        styleRefreshButton(btnRefreshAudit);

        auditButtonPanel.add(btnViewDetails);
        auditButtonPanel.add(btnExportAudit);
        auditButtonPanel.add(btnClearFilter);
        auditButtonPanel.add(btnRefreshAudit);

        panel.add(filterPanel, BorderLayout.NORTH);
        panel.add(auditScroll, BorderLayout.CENTER);
        panel.add(auditButtonPanel, BorderLayout.SOUTH);

        // Add action listeners for audit
        btnFilter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                applyAuditFilter((String) actionTypeCombo.getSelectedItem(),
                               txtAuditStartDate.getText(), txtAuditEndDate.getText(),
                               txtUserFilter.getText());
            }
        });

        btnViewDetails.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                viewAuditDetails();
            }
        });

        btnExportAudit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                exportAuditLog();
            }
        });

        btnClearFilter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                clearAuditFilter(actionTypeCombo, txtAuditStartDate, txtAuditEndDate, txtUserFilter);
            }
        });

        btnRefreshAudit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                refreshAuditData();
            }
        });

        return panel;
    }

    private void loadSampleData() {
        loadSampleReports();
        loadSampleAuditLogs();
    }

    private void loadSampleReports() {
        reportsModel.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy HH:mm");
        
        // Sample generated reports
        reportsModel.addRow(new Object[]{1, "Booking Summary", "2025-01-01 to 2025-01-31", "admin", sdf.format(new Date()), "COMPLETED"});
        reportsModel.addRow(new Object[]{2, "Revenue Report", "2025-01-01 to 2025-01-31", "admin", sdf.format(new Date(System.currentTimeMillis() - 86400000)), "COMPLETED"});
        reportsModel.addRow(new Object[]{3, "Trip Performance", "2025-01-01 to 2025-01-15", "manager", sdf.format(new Date(System.currentTimeMillis() - 172800000)), "COMPLETED"});
        reportsModel.addRow(new Object[]{4, "User Activity", "2025-01-20 to 2025-01-27", "admin", sdf.format(new Date(System.currentTimeMillis() - 259200000)), "COMPLETED"});
        reportsModel.addRow(new Object[]{5, "Vehicle Utilization", "2025-01-01 to 2025-01-31", "manager", sdf.format(new Date(System.currentTimeMillis() - 345600000)), "COMPLETED"});
    }

    private void loadSampleAuditLogs() {
        auditModel.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy HH:mm:ss");
        
        // Sample audit logs
        auditModel.addRow(new Object[]{1001, sdf.format(new Date()), "admin", "User Login", "Successful login to admin dashboard", "192.168.1.100", "SUCCESS"});
        auditModel.addRow(new Object[]{1002, sdf.format(new Date(System.currentTimeMillis() - 3600000)), "admin", "Booking Created", "Created booking #2051 for John Passenger", "192.168.1.100", "SUCCESS"});
        auditModel.addRow(new Object[]{1003, sdf.format(new Date(System.currentTimeMillis() - 7200000)), "manager", "User Modified", "Updated user profile for jane.driver", "192.168.1.101", "SUCCESS"});
        auditModel.addRow(new Object[]{1004, sdf.format(new Date(System.currentTimeMillis() - 10800000)), "admin", "Payment Processed", "Processed payment for booking #2051 - 10,000 RWF", "192.168.1.100", "SUCCESS"});
        auditModel.addRow(new Object[]{1005, sdf.format(new Date(System.currentTimeMillis() - 14400000)), "system", "Data Export", "Exported booking report for January 2025", "192.168.1.102", "COMPLETED"});
        auditModel.addRow(new Object[]{1006, sdf.format(new Date(System.currentTimeMillis() - 18000000)), "admin", "User Login", "Failed login attempt - invalid password", "192.168.1.105", "FAILED"});
        auditModel.addRow(new Object[]{1007, sdf.format(new Date(System.currentTimeMillis() - 21600000)), "manager", "Trip Modified", "Updated trip schedule for Kigali-Huye route", "192.168.1.101", "SUCCESS"});
    }

    private void generateReport(String reportType, String startDate, String endDate) {
        if (startDate.isEmpty() || endDate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both start and end dates.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Simulate report generation
        int newReportId = reportsModel.getRowCount() + 1;
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy HH:mm");
        
        reportsModel.addRow(new Object[]{
            newReportId, 
            reportType, 
            startDate + " to " + endDate,
            "admin", 
            sdf.format(new Date()),
            "COMPLETED"
        });

        JOptionPane.showMessageDialog(this, 
            "Report generated successfully!\n" +
            "Report ID: " + newReportId + "\n" +
            "Type: " + reportType + "\n" +
            "Period: " + startDate + " to " + endDate,
            "Report Generated", JOptionPane.INFORMATION_MESSAGE);
    }

    private void viewSelectedReport(JTextArea reportDetails) {
        int selectedRow = reportsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a report to view.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String reportType = (String) reportsModel.getValueAt(selectedRow, 1);
        String period = (String) reportsModel.getValueAt(selectedRow, 2);
        
        // Generate sample report content based on type
        StringBuilder reportContent = new StringBuilder();
        reportContent.append("TRANSPORT PORTAL - ").append(reportType.toUpperCase()).append("\n");
        reportContent.append("Period: ").append(period).append("\n");
        reportContent.append("Generated: ").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())).append("\n");
        reportContent.append("Generated By: admin\n");
        
        // Java 7 compatible way to repeat a string
        StringBuilder separator = new StringBuilder();
        for (int i = 0; i < 60; i++) {
            separator.append("=");
        }
        reportContent.append(separator.toString()).append("\n\n");

        if ("Booking Summary".equals(reportType)) {
            reportContent.append(generateBookingSummary());
        } else if ("Revenue Report".equals(reportType)) {
            reportContent.append(generateRevenueReport());
        } else if ("Trip Performance".equals(reportType)) {
            reportContent.append(generateTripPerformance());
        } else if ("User Activity".equals(reportType)) {
            reportContent.append(generateUserActivity());
        } else if ("Vehicle Utilization".equals(reportType)) {
            reportContent.append(generateVehicleUtilization());
        } else {
            reportContent.append("Report content not available for this type.");
        }

        reportContent.append("\n\n").append(separator.toString()).append("\n");
        reportContent.append("END OF REPORT");

        reportDetails.setText(reportContent.toString());
    }

    private String generateBookingSummary() {
        return "BOOKING SUMMARY REPORT\n" +
               "Total Bookings: 156\n" +
               "Confirmed: 142 (91.0%)\n" +
               "Pending: 8 (5.1%)\n" +
               "Cancelled: 6 (3.8%)\n\n" +
               "TOP ROUTES:\n" +
               "1. Kigali - Huye: 45 bookings\n" +
               "2. Kigali - Musanze: 38 bookings\n" +
               "3. Kigali - Rubavu: 32 bookings\n" +
               "4. Huye - Kigali: 25 bookings\n" +
               "5. Musanze - Kigali: 16 bookings\n\n" +
               "AVERAGE BOOKING VALUE: 7,450 RWF\n" +
               "PEAK BOOKING TIME: 08:00 - 10:00 AM";
    }

    private String generateRevenueReport() {
        return "REVENUE REPORT\n" +
               "Total Revenue: 1,162,500 RWF\n" +
               "Total Transactions: 156\n" +
               "Average Transaction: 7,450 RWF\n\n" +
               "REVENUE BY PAYMENT METHOD:\n" +
               "• Mobile Money: 845,000 RWF (72.7%)\n" +
               "• Credit Card: 245,000 RWF (21.1%)\n" +
               "• Cash: 72,500 RWF (6.2%)\n\n" +
               "DAILY REVENUE TREND:\n" +
               "• Monday: 185,000 RWF\n" +
               "• Tuesday: 167,500 RWF\n" +
               "• Wednesday: 198,000 RWF\n" +
               "• Thursday: 215,000 RWF\n" +
               "• Friday: 245,000 RWF\n" +
               "• Saturday: 105,000 RWF\n" +
               "• Sunday: 47,000 RWF";
    }

    private String generateTripPerformance() {
        return "TRIP PERFORMANCE REPORT\n" +
               "Total Trips Scheduled: 89\n" +
               "Completed: 82 (92.1%)\n" +
               "Ongoing: 4 (4.5%)\n" +
               "Cancelled: 3 (3.4%)\n\n" +
               "ON-TIME PERFORMANCE: 94.3%\n" +
               "AVERAGE OCCUPANCY RATE: 78.2%\n\n" +
               "TOP PERFORMING DRIVERS:\n" +
               "1. John Driver: 25 trips, 98% rating\n" +
               "2. Jane Smith: 22 trips, 96% rating\n" +
               "3. Mike Johnson: 18 trips, 94% rating\n\n" +
               "VEHICLE UTILIZATION:\n" +
               "• RAA 123A: 85% utilization\n" +
               "• RAB 456B: 78% utilization\n" +
               "• RAC 789C: 72% utilization";
    }

    private String generateUserActivity() {
        return "USER ACTIVITY REPORT\n" +
               "Total Users: 243\n" +
               "Active This Month: 187 (77.0%)\n" +
               "New Registrations: 28\n\n" +
               "USER DISTRIBUTION BY ROLE:\n" +
               "• Passengers: 215 (88.5%)\n" +
               "• Drivers: 18 (7.4%)\n" +
               "• Administrators: 5 (2.1%)\n" +
               "• Managers: 5 (2.1%)\n\n" +
               "TOP ACTIVITIES:\n" +
               "• Bookings Made: 156\n" +
               "• Profile Updates: 89\n" +
               "• Password Changes: 45\n" +
               "• Login Sessions: 1,234\n\n" +
               "USER SATISFACTION: 4.5/5.0";
    }

    private String generateVehicleUtilization() {
        return "VEHICLE UTILIZATION REPORT\n" +
               "Total Vehicles: 8\n" +
               "Active: 6 (75.0%)\n" +
               "In Maintenance: 2 (25.0%)\n\n" +
               "UTILIZATION BY VEHICLE:\n" +
               "1. RAA 123A (Volcano Bus): 92% - 45 trips\n" +
               "2. RAB 456B (RITCO Coach): 88% - 38 trips\n" +
               "3. RAC 789C (Express Van): 85% - 32 trips\n" +
               "4. RAD 012D (Mini Bus): 76% - 28 trips\n" +
               "5. RAE 345E (Luxury Coach): 68% - 22 trips\n\n" +
               "MAINTENANCE SCHEDULE:\n" +
               "• Next Service: RAA 123A (in 1,200 km)\n" +
               "• Last Service: RAB 456B (500 km ago)\n" +
               "• Due for Inspection: RAC 789C (next week)";
    }

    private void exportReportToPDF() {
        JOptionPane.showMessageDialog(this, 
            "PDF export functionality would be implemented here.\n" +
            "This would generate a formatted PDF document of the selected report.",
            "Export to PDF", JOptionPane.INFORMATION_MESSAGE);
    }

    private void exportReportToExcel() {
        JOptionPane.showMessageDialog(this, 
            "Excel export functionality would be implemented here.\n" +
            "This would generate an Excel spreadsheet with the report data.",
            "Export to Excel", JOptionPane.INFORMATION_MESSAGE);
    }

    private void refreshReportsData() {
        loadSampleReports();
        JOptionPane.showMessageDialog(this, "Reports data refreshed successfully!", "Refresh", JOptionPane.INFORMATION_MESSAGE);
    }

    private void applyAuditFilter(String actionType, String startDate, String endDate, String userFilter) {
        // In a real application, this would filter the audit logs from the database
        JOptionPane.showMessageDialog(this, 
            "Applied filter:\n" +
            "Action Type: " + actionType + "\n" +
            "Date Range: " + startDate + " to " + endDate + "\n" +
            "User: " + (userFilter.isEmpty() ? "All" : userFilter),
            "Filter Applied", JOptionPane.INFORMATION_MESSAGE);
    }

    private void viewAuditDetails() {
        int selectedRow = auditTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an audit log to view details.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int auditId = (Integer) auditModel.getValueAt(selectedRow, 0);
        String timestamp = (String) auditModel.getValueAt(selectedRow, 1);
        String user = (String) auditModel.getValueAt(selectedRow, 2);
        String action = (String) auditModel.getValueAt(selectedRow, 3);
        String description = (String) auditModel.getValueAt(selectedRow, 4);
        String ipAddress = (String) auditModel.getValueAt(selectedRow, 5);
        String status = (String) auditModel.getValueAt(selectedRow, 6);

        String details = String.format(
            "AUDIT LOG DETAILS\n\n" +
            "ID: %d\n" +
            "Timestamp: %s\n" +
            "User: %s\n" +
            "Action: %s\n" +
            "Description: %s\n" +
            "IP Address: %s\n" +
            "Status: %s\n\n" +
            "Additional Information:\n" +
            "• Session ID: SESS%06d\n" +
            "• User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)\n" +
            "• Location: Kigali, Rwanda\n" +
            "• Duration: 45 minutes",
            auditId, timestamp, user, action, description, ipAddress, status, auditId
        );

        JTextArea textArea = new JTextArea(details);
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(500, 300));
        
        JOptionPane.showMessageDialog(this, scrollPane, "Audit Log Details", JOptionPane.INFORMATION_MESSAGE);
    }

    private void exportAuditLog() {
        JOptionPane.showMessageDialog(this, 
            "Audit log export functionality would be implemented here.\n" +
            "This would generate a CSV or text file with all audit trail data.",
            "Export Audit Log", JOptionPane.INFORMATION_MESSAGE);
    }

    private void clearAuditFilter(JComboBox<String> actionTypeCombo, JTextField startDate, 
                                 JTextField endDate, JTextField userFilter) {
        actionTypeCombo.setSelectedIndex(0);
        startDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        endDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        userFilter.setText("");
        JOptionPane.showMessageDialog(this, "All filters cleared.", "Clear Filter", JOptionPane.INFORMATION_MESSAGE);
    }

    private void refreshAuditData() {
        loadSampleAuditLogs();
        JOptionPane.showMessageDialog(this, "Audit data refreshed successfully!", "Refresh", JOptionPane.INFORMATION_MESSAGE);
    }

    // BUTTON STYLING METHODS - ALL WITH BLACK TEXT
    private void styleAddButton(final JButton btn) {
        btn.setBackground(new Color(40, 167, 69)); // GREEN
        btn.setForeground(Color.BLACK); // CHANGED TO BLACK
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(33, 136, 56));
                btn.setForeground(Color.BLACK); // Keep black on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(40, 167, 69));
                btn.setForeground(Color.BLACK); // Keep black on exit
            }
        });
    }

    private void styleEditButton(final JButton btn) {
        btn.setBackground(new Color(0, 123, 255)); // BLUE
        btn.setForeground(Color.BLACK); // CHANGED TO BLACK
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(0, 105, 217));
                btn.setForeground(Color.BLACK); // Keep black on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(0, 123, 255));
                btn.setForeground(Color.BLACK); // Keep black on exit
            }
        });
    }

    private void styleDeleteButton(final JButton btn) {
        btn.setBackground(new Color(220, 53, 69)); // RED
        btn.setForeground(Color.BLACK); // CHANGED TO BLACK
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(200, 35, 51));
                btn.setForeground(Color.BLACK); // Keep black on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(220, 53, 69));
                btn.setForeground(Color.BLACK); // Keep black on exit
            }
        });
    }

    private void styleRefreshButton(final JButton btn) {
        btn.setBackground(new Color(108, 117, 125)); // GRAY
        btn.setForeground(Color.BLACK); // CHANGED TO BLACK
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(90, 98, 104));
                btn.setForeground(Color.BLACK); // Keep black on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(108, 117, 125));
                btn.setForeground(Color.BLACK); // Keep black on exit
            }
        });
    }
}